codecov:
  notify:
    require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: 80..100

    status:
      project: true
      patch: true
      changes: true

  comment:
    layout: "header, diff, changes, sunburst, uncovered"
    behavior: default  # update if exists else create new
